//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module4_BCL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Module4_BCL.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} don&apos;t satisfy to any pattern, Destination Folder: {1}.
        /// </summary>
        internal static string DefaultPatternFound {
            get {
                return ResourceManager.GetString("DefaultPatternFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Ctrl+C or Ctrl+Break to exit.
        /// </summary>
        internal static string ExitHotKeysMessage {
            get {
                return ResourceManager.GetString("ExitHotKeysMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exited successfully.
        /// </summary>
        internal static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE FOUND: {0}, Created: {1}, Path: {2}.
        /// </summary>
        internal static string FileFindedMessage {
            get {
                return ResourceManager.GetString("FileFindedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE MOVED: {0} to {1}.
        /// </summary>
        internal static string FileSuccessfullMovedMessage {
            get {
                return ResourceManager.GetString("FileSuccessfullMovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Folder undefined.
        /// </summary>
        internal static string NotDefinedDefaultFolder {
            get {
                return ResourceManager.GetString("NotDefinedDefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} satisfy to Pattern: {1}, Destination Folder: {2}.
        /// </summary>
        internal static string PatternFoundMessage {
            get {
                return ResourceManager.GetString("PatternFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} wasn&apos;t moved.
        /// </summary>
        internal static string UnableToMoveFile {
            get {
                return ResourceManager.GetString("UnableToMoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Rename File.
        /// </summary>
        internal static string UnableToRenameFile {
            get {
                return ResourceManager.GetString("UnableToRenameFile", resourceCulture);
            }
        }
    }
}
